services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
        - sss-db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    sss-db-data:
        driver: local